/* exe0607. Prime numbers can also be generated by an algorithm
 * known as the Sieve of Eratosthenes. Write a program that
 * implements this algorithm. Have the progrm find all
 * prime numbers up to n = 150. What can you say about this algorithm
 * as compared to the ones used in the text for
 * calculating prime numbers?
 * Answer:
 * Sieve of Eratosthenes Algorithm To Display all
 * Prime Numbers Between 1 and n
 * Step 1: Define an array of integers P. Set all elements P[i] to 0, 2 <= i <= n.
 * Step 2: Set i to 2.
 * Step 3: If i > n, the algorithm terminates.
 * Step 4: If Pi is 0, then i is prime.
 * Step 5: For all positive integer values of j, such that i x j <= n, set Pixj to 1.
 * Step 6: Add 1 to i and go to step 3.
 * by Ron, Jan 2021 */

#include <stdio.h>

int main(void)
{
  int n = 150;
  int P[n];
  int i, j;

  for (i = 0; i < n; ++i)
    P[i] = 0;

  for (i = 2; i <= n; ++i) 
    for (j = 2; i * j <= n; ++j)
      P[i*j] = 1;

  for (i = 0; i < n; ++i)
    if (P[i] == 0)
      printf("%i ", i);
  printf("\n");

  return 0;
}
